package Pojo;
// Generated 9/02/2016 02:16:40 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Grupo generated by hbm2java
 */
public class Grupo  implements java.io.Serializable {


     private Integer gruCodigo;
     private String gruNombre;
     private String gruDescripcion;
     private String gruEstado;
     private Set productos = new HashSet(0);

    public Grupo() {
    }

	
    public Grupo(String gruNombre) {
        this.gruNombre = gruNombre;
    }
    public Grupo(String gruNombre, String gruDescripcion, String gruEstado, Set productos) {
       this.gruNombre = gruNombre;
       this.gruDescripcion = gruDescripcion;
       this.gruEstado = gruEstado;
       this.productos = productos;
    }
   
    public Integer getGruCodigo() {
        return this.gruCodigo;
    }
    
    public void setGruCodigo(Integer gruCodigo) {
        this.gruCodigo = gruCodigo;
    }
    public String getGruNombre() {
        return this.gruNombre;
    }
    
    public void setGruNombre(String gruNombre) {
        this.gruNombre = gruNombre;
    }
    public String getGruDescripcion() {
        return this.gruDescripcion;
    }
    
    public void setGruDescripcion(String gruDescripcion) {
        this.gruDescripcion = gruDescripcion;
    }
    public String getGruEstado() {
        return this.gruEstado;
    }
    
    public void setGruEstado(String gruEstado) {
        this.gruEstado = gruEstado;
    }
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }




}


