package Pojo;
// Generated 16/05/2016 08:25:28 PM by Hibernate Tools 4.3.1



/**
 * Movimientos generated by hbm2java
 */
public class Movimientos  implements java.io.Serializable {


     private int movCodigo;
     private Producto producto;
     private Users users;
     private String movAccion;
     private String movCantidad;

    public Movimientos() {
    }

	
    public Movimientos(int movCodigo) {
        this.movCodigo = movCodigo;
    }
    public Movimientos(int movCodigo, Producto producto, Users users, String movAccion, String movCantidad) {
       this.movCodigo = movCodigo;
       this.producto = producto;
       this.users = users;
       this.movAccion = movAccion;
       this.movCantidad = movCantidad;
    }
   
    public int getMovCodigo() {
        return this.movCodigo;
    }
    
    public void setMovCodigo(int movCodigo) {
        this.movCodigo = movCodigo;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getMovAccion() {
        return this.movAccion;
    }
    
    public void setMovAccion(String movAccion) {
        this.movAccion = movAccion;
    }
    public String getMovCantidad() {
        return this.movCantidad;
    }
    
    public void setMovCantidad(String movCantidad) {
        this.movCantidad = movCantidad;
    }




}


