package Pojo;
// Generated 9/02/2016 02:16:40 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Paginas generated by hbm2java
 */
public class Paginas  implements java.io.Serializable {


     private Integer pagid;
     private String pagname;
     private String pagurl;
     private String pagicono;
     private String pagestado;
     private Set permisoses = new HashSet(0);

    public Paginas() {
    }

	
    public Paginas(String pagname, String pagurl) {
        this.pagname = pagname;
        this.pagurl = pagurl;
    }
    public Paginas(String pagname, String pagurl, String pagicono, String pagestado, Set permisoses) {
       this.pagname = pagname;
       this.pagurl = pagurl;
       this.pagicono = pagicono;
       this.pagestado = pagestado;
       this.permisoses = permisoses;
    }
   
    public Integer getPagid() {
        return this.pagid;
    }
    
    public void setPagid(Integer pagid) {
        this.pagid = pagid;
    }
    public String getPagname() {
        return this.pagname;
    }
    
    public void setPagname(String pagname) {
        this.pagname = pagname;
    }
    public String getPagurl() {
        return this.pagurl;
    }
    
    public void setPagurl(String pagurl) {
        this.pagurl = pagurl;
    }
    public String getPagicono() {
        return this.pagicono;
    }
    
    public void setPagicono(String pagicono) {
        this.pagicono = pagicono;
    }
    public String getPagestado() {
        return this.pagestado;
    }
    
    public void setPagestado(String pagestado) {
        this.pagestado = pagestado;
    }
    public Set getPermisoses() {
        return this.permisoses;
    }
    
    public void setPermisoses(Set permisoses) {
        this.permisoses = permisoses;
    }




}


