package Pojo;
// Generated 9/02/2016 02:16:40 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Role generated by hbm2java
 */
public class Role  implements java.io.Serializable {


     private Integer rolid;
     private String rolname;
     private String roldesc;
     private String rolestado;
     private Set roleusrs = new HashSet(0);
     private Set permisoses = new HashSet(0);

    public Role() {
    }

	
    public Role(String rolestado) {
        this.rolestado = rolestado;
    }
    public Role(String rolname, String roldesc, String rolestado, Set roleusrs, Set permisoses) {
       this.rolname = rolname;
       this.roldesc = roldesc;
       this.rolestado = rolestado;
       this.roleusrs = roleusrs;
       this.permisoses = permisoses;
    }
   
    public Integer getRolid() {
        return this.rolid;
    }
    
    public void setRolid(Integer rolid) {
        this.rolid = rolid;
    }
    public String getRolname() {
        return this.rolname;
    }
    
    public void setRolname(String rolname) {
        this.rolname = rolname;
    }
    public String getRoldesc() {
        return this.roldesc;
    }
    
    public void setRoldesc(String roldesc) {
        this.roldesc = roldesc;
    }
    public String getRolestado() {
        return this.rolestado;
    }
    
    public void setRolestado(String rolestado) {
        this.rolestado = rolestado;
    }
    public Set getRoleusrs() {
        return this.roleusrs;
    }
    
    public void setRoleusrs(Set roleusrs) {
        this.roleusrs = roleusrs;
    }
    public Set getPermisoses() {
        return this.permisoses;
    }
    
    public void setPermisoses(Set permisoses) {
        this.permisoses = permisoses;
    }




}


