package Pojo;
// Generated 9/02/2016 02:16:40 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tipodescarga generated by hbm2java
 */
public class Tipodescarga  implements java.io.Serializable {


     private Integer tideCodigo;
     private String tideNombre;
     private String tideDescripcion;
     private String tideEstado;
     private Set productos = new HashSet(0);

    public Tipodescarga() {
    }

	
    public Tipodescarga(String tideNombre) {
        this.tideNombre = tideNombre;
    }
    public Tipodescarga(String tideNombre, String tideDescripcion, String tideEstado, Set productos) {
       this.tideNombre = tideNombre;
       this.tideDescripcion = tideDescripcion;
       this.tideEstado = tideEstado;
       this.productos = productos;
    }
   
    public Integer getTideCodigo() {
        return this.tideCodigo;
    }
    
    public void setTideCodigo(Integer tideCodigo) {
        this.tideCodigo = tideCodigo;
    }
    public String getTideNombre() {
        return this.tideNombre;
    }
    
    public void setTideNombre(String tideNombre) {
        this.tideNombre = tideNombre;
    }
    public String getTideDescripcion() {
        return this.tideDescripcion;
    }
    
    public void setTideDescripcion(String tideDescripcion) {
        this.tideDescripcion = tideDescripcion;
    }
    public String getTideEstado() {
        return this.tideEstado;
    }
    
    public void setTideEstado(String tideEstado) {
        this.tideEstado = tideEstado;
    }
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }




}


